---
development:
  :redis_provider: 'redis://rails_with_sidekiq_redis_1:6379/0'
  :database:
    :host: rails_with_sidekiq_db_1
    :name: rails_sidekiq_dev
    :username: postgres
    :password: rails_sidekiq

test:
  :redis_provider: 'redis://rails_with_sidekiq_redis_1:6379/0'
  :database:
    :host: rails_with_sidekiq_db_1
    :name: rails_sidekiq_test
    :username: postgres
    :password: rails_sidekiq

production:
  :database:
    :host: <%= ENV["DATABASE_URL"] %>
